 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wage_verifications", type: :request do
  # WageVerification. As you add validations to WageVerification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WageVerification.create! valid_attributes
      get wage_verifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wage_verification = WageVerification.create! valid_attributes
      get wage_verification_url(wage_verification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wage_verification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      wage_verification = WageVerification.create! valid_attributes
      get edit_wage_verification_url(wage_verification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WageVerification" do
        expect {
          post wage_verifications_url, params: { wage_verification: valid_attributes }
        }.to change(WageVerification, :count).by(1)
      end

      it "redirects to the created wage_verification" do
        post wage_verifications_url, params: { wage_verification: valid_attributes }
        expect(response).to redirect_to(wage_verification_url(WageVerification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WageVerification" do
        expect {
          post wage_verifications_url, params: { wage_verification: invalid_attributes }
        }.to change(WageVerification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wage_verifications_url, params: { wage_verification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wage_verification" do
        wage_verification = WageVerification.create! valid_attributes
        patch wage_verification_url(wage_verification), params: { wage_verification: new_attributes }
        wage_verification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wage_verification" do
        wage_verification = WageVerification.create! valid_attributes
        patch wage_verification_url(wage_verification), params: { wage_verification: new_attributes }
        wage_verification.reload
        expect(response).to redirect_to(wage_verification_url(wage_verification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wage_verification = WageVerification.create! valid_attributes
        patch wage_verification_url(wage_verification), params: { wage_verification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wage_verification" do
      wage_verification = WageVerification.create! valid_attributes
      expect {
        delete wage_verification_url(wage_verification)
      }.to change(WageVerification, :count).by(-1)
    end

    it "redirects to the wage_verifications list" do
      wage_verification = WageVerification.create! valid_attributes
      delete wage_verification_url(wage_verification)
      expect(response).to redirect_to(wage_verifications_url)
    end
  end
end
